do_train = false
do_eval = false
do_test = true
dataset_names = ["qnli", "mnli"]
model_name_or_path = "t5-base"
data_tokenizer_name_or_path = "t5-base"
max_target_length = 128
per_device_eval_batch_size = 32
report_to = "wandb"
num_virtual_tokens = 50
wandb_project = "eval_arithmetics"
max_source_length = 256
split_validation_test = true
origin_prompts = ["origin"]
predict_with_generate = true
evaluation_strategy = "steps"
eval_steps = 10
logging_strategy = "epoch"
save_strategy = "no"
output_dir = "saves/eval_addition" 