do_train = true
do_eval = true
do_test = true
test_dataset_names = ["qnli", "mnli"]
model_name_or_path = "t5-base"
tokenizer_name_or_path = "t5-base"
max_target_length = 128
per_device_eval_batch_size = 32
per_device_train_batch_size = 32
report_to = "wandb"
wandb_project = "arithmetics"
max_source_length = 256
split_validation_test = true
output_dir = "fft_mnli_qnli"
predict_with_generate = true
evaluation_strategy = "steps"
eval_steps = 100
save_steps= 100
logging_strategy = "epoch"
save_strategy = "steps"
load_best_model_at_end = true
metric_for_best_model= "average_metrics"
save_total_limit= 1