do_train = true
do_eval = true
do_test = true
dataset_names = ["sst2"]
model_name_or_path = "t5-base"
tokenizer_name_or_path = "t5-base"
max_target_length = 128
per_device_eval_batch_size = 32
per_device_train_batch_size = 32
report_to = "wandb"
wandb_project = "arithmetics"
max_source_length = 256
split_validation_test = true
output_dir = "saves/prompt_tuning"
predict_with_generate = true
evaluation_strategy = "steps"
save_strategy = "steps"
logging_strategy = "epoch"
eval_steps = 100
save_steps= 100
load_best_model_at_end = true
metric_for_best_model = "average_loss"
save_total_limit = 1
task_type = "SEQ_2_SEQ_LM"
num_virtual_tokens = 50
weight_decay = 1e-5
warmup_steps = 500
num_train_epochs = 10
learning_rate = 0.3
# max_train_samples = 1000
# max_valid_samples = 500
# max_test_samples = 500